FROM ubuntu:18.04

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080/api

RUN apt-get update && \
    apt-get install curl -y && \
    curl -sL https://deb.nodesource.com/setup_lts.x | bash - && \    
    apt-get install -y nodejs && \
    apt-get remove curl -y && \
    npm install && \
    npm install -g serve &&\
    npm run build && \
    useradd -m appuser && \
    chown appuser .

USER appuser

CMD [ "serve", "-s", "-l", "5000", "build" ]