FROM node:14

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

RUN npm install

ENV REACT_APP_BACKEND_URL=http://localhost:8080/api

RUN npm install -g serve

RUN npm run build

RUN useradd -m appuser

RUN chown appuser .

USER appuser

CMD [ "serve", "-s", "-l", "5000", "build" ]