version: '3.5'

services:
  back:
    build:
      context: ./ml-kurkkumopo-backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - model:/src/model
    container_name: kurkkumopo-backend
  front:
    build:
      context: ./ml-kurkkumopo-frontend
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    container_name: kurkkumopo-frontend
  training:
    build:
      context: ./ml-kurkkumopo-training
      dockerfile: Dockerfile
    volumes:
      - model:/src/model
      - imgs:/src/imgs
    container_name: kurkkumopo-training
      
volumes:
  imgs:
  model:
