version: '3' 

services: 
    youtube-dl-ubuntu:  
      image: devopsdockeruh/simple-web-service
      build: . 
      volumes: 
        - ./logs/logs.txt:/usr/src/app/text.log
      ports:
      - 8000:8000
      container_name: simple-web-service