FROM node:14-alpine as build-stage

EXPOSE 5000

WORKDIR /usr/src/app

COPY . .

ENV REACT_APP_BACKEND_URL=http://localhost:8080/api

RUN npm install && \
    npm run build

FROM node:14-alpine

WORKDIR /usr/src/app

COPY --from=build-stage /usr/src/app/build /usr/src/app/build

RUN npm install -g serve && \
    adduser -S appuser && \
    chown appuser .

USER appuser

CMD [ "serve", "-s", "-l", "5000", "build" ]